#!/bin/bash
# Generated by Cobalt GenerateBasScripts
#
# Parameters (for debugging purposes):
#
# nodes = 1
# nparts = 1
# blocks = 12
# blockSize = 1024
# cores = 12
#
#
# Start Apache Spark Cluster
#

JOB_LOG=$HOME/logs/$COBALT_JOBID.txt
JOB_JSON=$HOME/logs/$COBALT_JOBID.json
JOB_XML=$HOME/logs/$COBALT_JOBID.xml

pushd $HOME/code/spark
cat $COBALT_NODEFILE > conf/slaves
cat $COBALT_NODEFILE >> $JOB_LOG
./sbin/start-all.sh
NODES=`wc -l conf/slaves | cut -d" " -f1`
popd

MASTER=`hostname`

echo "# Spark is now running with $NODES workers:" >> $JOB_LOG
echo "#"
echo "export SPARK_STATUS_URL=http://$MASTER.cooley.pub.alcf.anl.gov:8000" >> $JOB_LOG
echo "export SPARK_MASTER_URI=spark://$MASTER:7077" >> $JOB_LOG

SPARK_MASTER_URI=spark://$MASTER:7077
SPARK_HOME=$HOME/code/spark

#
# Done Initializing Apache Spark
#
#
# Submit Application on Spark
#

for ASSEMBLY in $(find . -type f -name git-all-spark-scala-assembly*.jar)
do
   echo "Running: "$SPARK_HOME/bin/spark-submit --master $SPARK_MASTER_URI $ASSEMBLY "$@" >> $JOB_LOG

   $SPARK_HOME/bin/spark-submit --master $SPARK_MASTER_URI $ASSEMBLY "$@" >> $JOB_LOG

done

#
# Done Submitting Application on Spark
#
